name: toolkit-audit
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  build:
    name: Audit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: npm install
      run: npm install

    - name: audit
      run: npm run audit-moderate
